package com.github.javlock.system.auditd;

public enum _AUDIT_TYPE_NAME {
	AVC, BPF, CONFIG_CHANGE, CRED_ACQ, CRED_DISP, PROCTITLE, CRED_REFR, CWD, EVENT_LISTENER, PATH, NETFILTER_CFG,
	SERVICE_START, SERVICE_STOP, SYSCALL, SYSTEM_BOOT, SYSTEM_SHUTDOWN, USER_ACCT, USER_AUTH, USER_END, USER_START,
	USYS_CONFIG, RESP_ACCT_LOCK, ANOM_LOGIN_FAILURES, ANOM_ABEND
}
